feat: create a Rust sample plugin for A/B testing
GoogleCloudPlatform/service-extensions pull request #140
Opened 2024-12-12 14:58 UTC by pweiber

Rust version for the A/B testing.

If the hash value is less than or equal to the percentile, the request is served by v2 file. Otherwise, it is served by its original file.

2025-01-29 12:54 UTC, dallen68 requested changes

2025-01-29 12:54 UTC, dallen68 commented on plugins/samples/ab_testing/plugin.rs
> +    let sum: u64 = user.bytes().map(u64::from).sum();
Is there a reason why we aren't using the default hashing implementation for slices in Rust? https://doc.rust-lang.org/stable/std/hash/trait.Hash.html#method.hash_slice

2025-01-31 17:23 UTC, pweiber commented on plugins/samples/ab_testing/plugin.rs
> +    let sum: u64 = user.bytes().map(u64::from).sum();
I did this way because the tests were based on the c++ code, for one of them if I used the default hashing I was getting different values

for the "WithHashAboveThresholdKeepTheSame"

C++ computes std::hash("userAAA") % 100 = 63 (63 > 50 → no redirect).
Rust’s DefaultHasher produces a different value (e.g., hash % 100 ≤ 50 → redirect).

Using like this I'm getting
// For "userAAA": 642 + 21 = 663 → 63%100

Let me know if it is fine to keep it like this or if we should adjust for both

2025-02-05 16:59 UTC, dallen68 approved these changes

2025-02-05 16:59 UTC, dallen68 commented on plugins/samples/ab_testing/plugin.rs
> +    let sum: u64 = user.bytes().map(u64::from).sum();
Sounds good. Maybe add a comment saying why were are hashing by hand instead of using the rust standard library.

2025-02-06 17:51 UTC, pweiber commented
@dallen68 Let me know if the comment is fine like that or if we should change something

2025-02-10 17:12 UTC, merged